name: Amazing Husky
favicon: null
layout_spectrum: 0.25708961160853505
typography_spectrum: 0.1613626265898347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4220736320130527
  lightness: 0.027156859869137406
  saturation: 0.5474323893431574
  rhythmicContrast: 0.0678945742547512
purpose: []
